services:
  ntechauth:
    image: ${DOCKER_REGISTRY-}ntechauth
    build:
      context: .
      dockerfile: NTech.Auth/Dockerfile
      args:
        NUGET_URL: "https://nuget.pkg.github.com/nhave/index.json"
        NUGET_AUTH_TOKEN: ${GITHUB_PAT}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTPS_PORT = 443
      - OpenId__SigningKeyLocation=${OPENID_SIGNING_KEY_LOCATION}
      - OpenId__EncryptionKey=${OPENID_ENCRYPTION_KEY}
      - OpenId__Authority=${OPENID_AUTHORITY}
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION_STRING}
      - Defaults__Username=${DEFAULT_USERNAME}
      - Defaults__Password=${DEFAULT_PASSWORD}
      - Defaults__LastName=${DEFAULT_LASTNAME}
      - Defaults__FirstName=${DEFAULT_FIRSTNAME}
      - Defaults__Email=${DEFAULT_EMAIL}
      - Files__FilePath=/etc/resources
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT_HTTP}:8080"
    volumes:
      - ${HOST_KEYS_PATH}:/etc/keys:ro
      - ${HOST_RESOURCES_PATH}:/etc/resources
